name: Greetings

on: [pull_request_target, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for submitting your issue."
        pr-message: "Thank you for creating a PR."

  push-message:
    if: github.event_name == 'push'  # Only run on push events
    runs-on: ubuntu-latest
    steps:
      - name: Send Push Message
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
          -d '{"body": "A new push was made to this repository!"}'
